#!/bin/bash

info="transform the output of text"
depends=( figlet lolcat )

if [ $# -ne 0 ]; then
	echo -e "$@" | ${depends[0]} | ${depends[1]} && exit 0
fi

echo "$(basename $0) - ${info}"
echo
echo "USAGE:"
echo "   $(basename $0) [TEXT]"
echo
echo "EXAMPLE:"
echo "   $(basename $0) example text"
echo "   $(basename $0) \"\\\n another example \\\n\""
echo
exit 1
